name: CI

# Controls when the workflow will run
on: push

# Cancels all previous runs of this workflow and runs a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Test each aspect of the application
jobs:
  static-test:
    name: 🔬 Static tests
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: ⬣ Lint
        run: vp lint

      - name: ʦ TypeScript
        run: vp run -r typecheck

  unit-test:
    needs: [static-test]
    name: 🚦 Unit test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: 🧪 Run unit tests
        run: vp run test:unit

  test-e2e:
    needs: [static-test]
    name: 🚥 E2E tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: 🎭 Run Playwright tests
        run: vp run -r test:e2e

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
