name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp run ready
