name: Tests

on:
  workflow_call:

env:
  VARLOCK_ENV: "test"

  # Test each aspect of the application
jobs:
  static-test:
    name: 🔬 Static tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: ⬣ Lint & type check
        run: vp lint

  unit-test:
    needs: [static-test]
    name: 🚦 Unit test
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: 🧪 Run unit tests
        run: vp test

  test-e2e:
    needs: [static-test]
    name: 🚥 E2E tests
    timeout-minutes: 5
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⚡ Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Install Playwright Browsers
        run: vp run setup:playwright

      - name: 🎭 Run Playwright tests
        run: vp run -r test:e2e

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
